#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sphinx_rtd_theme

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

import os.path
import sys

# NOTE: this is important, must set the path correctly.
sys.path.insert(0, os.path.abspath('../../src'))

# Determine whether the documentation is being built on Read The Docs.
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

# Avoid build errors on Read The Docs (requires Sphinx 1.3 or newer).
# See http://read-the-docs.readthedocs.io/en/latest/faq.html for details.
if on_rtd:
    autodoc_mock_imports = ['numpy', 'pandas']

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.mathjax',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'mslt_port'
copyright = '2018, James Collins, Rob Moss, Anja Mizdrak'
author = 'James Collins, Rob Moss, Anja Mizdrak'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.0'
# The full version, including alpha/beta/rc tags.
release = '0.0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# Define common RST content, such as the link to the master repository.
rst_epilog = """
.. _Anaconda: https://www.anaconda.com/download/
.. _MSLT: https://github.com/collijk/mslt_port
.. _Vivarium: https://github.com/ihmeuw/vivarium
.. _Vivarium Public Health: https://github.com/ihmeuw/vivarium_public_health
"""

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Show both the class docstring and the __init__ method's docstring.
autoclass_content = 'both'


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
